In [2]:
import pandas as pd

# Read CSV Files

## Applicants Data

In [16]:
df_applicants = pd.read_csv("./data/applicants.csv")

C:\Users\victo\AppData\Local\Temp\ipykernel_9408\486818049.py:1: DtypeWarning: Columns (45,46,51,56,57) have mixed types. Specify dtype option on import or set low_memory=False.
  df_applicants = pd.read_csv("./data/applicants.csv")

In [17]:
df_applicants[:5]

,id,infos_basicas_telefone_recado,infos_basicas_telefone,infos_basicas_objetivo_profissional,infos_basicas_data_criacao,infos_basicas_inserido_por,infos_basicas_email,infos_basicas_local,infos_basicas_sabendo_de_nos_por,infos_basicas_data_atualizacao,...,cargo_atual_id_ibrati,cargo_atual_email_corporativo,cargo_atual_cargo_atual,cargo_atual_projeto_atual,cargo_atual_cliente,cargo_atual_unidade,cargo_atual_data_admissao,cargo_atual_data_ultima_promocao,cargo_atual_nome_superior_imediato,cargo_atual_email_superior_imediato
0,31000,NaN,(11) 97048-2708,NaN,10-11-2021 07:29:49,Luna Correia,carolina_aparecida@gmail.com,NaN,NaN,10-11-2021 07:29:49,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,31001,NaN,(11) 93723-4396,Analista Administrativo,10-11-2021 08:56:16,Laura Pacheco,eduardo_rios@hotmail.com,"São Paulo, São Paulo",Outros,11-11-2021 11:10:31,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,31002,NaN,(11) 92399-9824,Administrativo | Financeiro,10-11-2021 09:01:00,Laura Pacheco,pedro_henrique_carvalho@gmail.com,"São Paulo, São Paulo",Anúncio,10-11-2021 11:42:36,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,31003,NaN,(11) 98100-1727,Área administrativa,10-11-2021 09:08:13,Laura Pacheco,thiago_barbosa@hotmail.com,"São Paulo, São Paulo",Site de Empregos,10-11-2021 16:04:51,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,31004,NaN,(11) 92517-2678,NaN,10-11-2021 09:18:46,Maria Clara Pires,diogo_das_neves@hotmail.com,NaN,NaN,10-11-2021 09:22:03,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_applicants.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42482 entries, 0 to 42481
Data columns (total 58 columns):
 #   Column                                            Non-Null Count  Dtype
---  ------                                            --------------  -----
 0   id                                                42482 non-null  int64
 1   infos_basicas_telefone_recado                     0 non-null      float64
 2   infos_basicas_telefone                            41026 non-null  object
 3   infos_basicas_objetivo_profissional               28066 non-null  object
 4   infos_basicas_data_criacao                        42480 non-null  object
 5   infos_basicas_inserido_por                        42482 non-null  object
 6   infos_basicas_email                               42482 non-null  object
 7   infos_basicas_local                               17008 non-null  object
 8   infos_basicas_sabendo_de_nos_por                  20376 non-null  object
 9   infos_basicas_data_atualizacao                    42480 non-null  object
 10  infos_basicas_codigo_profissional                 42482 non-null  int64
 11  infos_basicas_nome                                42482 non-null  object
 12  informacoes_pessoais_data_aceite                  42482 non-null  object
 13  informacoes_pessoais_nome                         42482 non-null  object
 14  informacoes_pessoais_cpf                          0 non-null      float64
 15  informacoes_pessoais_fonte_indicacao              42482 non-null  object
 16  informacoes_pessoais_email                        42482 non-null  object
 17  informacoes_pessoais_email_secundario             0 non-null      float64
 18  informacoes_pessoais_data_nascimento              42480 non-null  object
 19  informacoes_pessoais_telefone_celular             41026 non-null  object
 20  informacoes_pessoais_telefone_recado              0 non-null      float64
 21  informacoes_pessoais_sexo                         7184 non-null   object
 22  informacoes_pessoais_estado_civil                 7451 non-null   object
 23  informacoes_pessoais_pcd                          6321 non-null   object
 24  informacoes_pessoais_endereco                     16928 non-null  object
 25  informacoes_pessoais_skype                        0 non-null      float64
 26  informacoes_pessoais_url_linkedin                 0 non-null      float64
 27  informacoes_pessoais_facebook                     0 non-null      float64
 28  informacoes_profissionais_titulo_profissional     28066 non-null  object
 29  informacoes_profissionais_area_atuacao            6751 non-null   object
 30  informacoes_profissionais_conhecimentos_tecnicos  3352 non-null   object
 31  informacoes_profissionais_certificacoes           528 non-null    object
 32  informacoes_profissionais_outras_certificacoes    898 non-null    object
 33  informacoes_profissionais_remuneracao             20135 non-null  object
 34  informacoes_profissionais_nivel_profissional      80 non-null     object
 35  formacao_e_idiomas_nivel_academico                8094 non-null   object
 36  formacao_e_idiomas_nivel_ingles                   6844 non-null   object
 37  formacao_e_idiomas_nivel_espanhol                 6687 non-null   object
 38  formacao_e_idiomas_outro_idioma                   42482 non-null  object
 39  cv_pt                                             29051 non-null  object
 40  cv_en                                             0 non-null      float64
 41  formacao_e_idiomas_instituicao_ensino_superior    1249 non-null   object
 42  formacao_e_idiomas_cursos                         6139 non-null   object
 43  formacao_e_idiomas_ano_conclusao                  7209 non-null   float64
 44  informacoes_pessoais_download_cv                  5562 non-null   object
 45  informacoes_profissionais_qualificacoes           1 non-null      object
 46  informacoes_profissionais_experiencias            1 non-null      object
 47  formacao_e_idiomas_outro_curso                    809 non-null    object
 48  cargo_atual_id_ibrati                             396 non-null    float64
 49  cargo_atual_email_corporativo                     0 non-null      float64
 50  cargo_atual_cargo_atual                           398 non-null    object
 51  cargo_atual_projeto_atual                         1 non-null      object
 52  cargo_atual_cliente                               398 non-null    object
 53  cargo_atual_unidade                               397 non-null    object
 54  cargo_atual_data_admissao                         741 non-null    object
 55  cargo_atual_data_ultima_promocao                  741 non-null    object
 56  cargo_atual_nome_superior_imediato                1 non-null      object
 57  cargo_atual_email_superior_imediato               1 non-null      object
dtypes: float64(11), int64(2), object(45)
memory usage: 18.8+ MB

## Vagas Data

In [9]:
df_vagas = pd.read_csv("./data/vagas.csv")

In [10]:
df_vagas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14081 entries, 0 to 14080
Data columns (total 45 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   id                                                    14081 non-null  int64
 1   informacoes_basicas_data_requicisao                   14081 non-null  object
 2   informacoes_basicas_limite_esperado_para_contratacao  14081 non-null  object
 3   informacoes_basicas_titulo_vaga                       14081 non-null  object
 4   informacoes_basicas_vaga_sap                          14081 non-null  object
 5   informacoes_basicas_cliente                           14081 non-null  object
 6   informacoes_basicas_solicitante_cliente               14081 non-null  object
 7   informacoes_basicas_empresa_divisao                   14081 non-null  object
 8   informacoes_basicas_requisitante                      14081 non-null  object
 9   informacoes_basicas_analista_responsavel              14081 non-null  object
 10  informacoes_basicas_tipo_contratacao                  13477 non-null  object
 11  informacoes_basicas_prazo_contratacao                 9779 non-null   object
 12  informacoes_basicas_objetivo_vaga                     10994 non-null  object
 13  informacoes_basicas_prioridade_vaga                   10031 non-null  object
 14  informacoes_basicas_origem_vaga                       8938 non-null   object
 15  informacoes_basicas_superior_imediato                 14039 non-null  object
 16  informacoes_basicas_nome                              133 non-null    object
 17  informacoes_basicas_telefone                          3 non-null      object
 18  perfil_vaga_pais                                      14081 non-null  object
 19  perfil_vaga_estado                                    14070 non-null  object
 20  perfil_vaga_cidade                                    14030 non-null  object
 21  perfil_vaga_bairro                                    1091 non-null   object
 22  perfil_vaga_regiao                                    1412 non-null   object
 23  perfil_vaga_local_trabalho                            14081 non-null  int64
 24  perfil_vaga_vaga_especifica_para_pcd                  12133 non-null  object
 25  perfil_vaga_faixa_etaria                              14081 non-null  object
 26  perfil_vaga_horario_trabalho                          138 non-null    object
 27  perfil_vaga_nivel profissional                        14081 non-null  object
 28  perfil_vaga_nivel_academico                           14081 non-null  object
 29  perfil_vaga_nivel_ingles                              14081 non-null  object
 30  perfil_vaga_nivel_espanhol                            12777 non-null  object
 31  perfil_vaga_outro_idioma                              373 non-null    object
 32  perfil_vaga_areas_atuacao                             14066 non-null  object
 33  perfil_vaga_principais_atividades                     14077 non-null  object
 34  perfil_vaga_competencia_tecnicas_e_comportamentais    14074 non-null  object
 35  perfil_vaga_demais_observacoes                        9805 non-null   object
 36  perfil_vaga_viagens_requeridas                        7083 non-null   object
 37  perfil_vaga_equipamentos_necessarios                  4246 non-null   object
 38  beneficios_valor_venda                                14081 non-null  object
 39  beneficios_valor_compra_1                             14078 non-null  object
 40  beneficios_valor_compra_2                             47 non-null     object
 41  informacoes_basicas_data_inicial                      4456 non-null   object
 42  informacoes_basicas_data_final                        4456 non-null   object
 43  perfil_vaga_habilidades_comportamentais_necessarias   2662 non-null   object
 44  informacoes_basicas_nome_substituto                   272 non-null    object
dtypes: int64(2), object(43)
memory usage: 4.8+ MB

In [11]:
df_vagas.describe()

                 id  perfil_vaga_local_trabalho
count  14081.000000                14081.000000
mean    7105.029046                 1887.436972
std     4108.161470                  316.069118
min        2.000000                 1000.000000
25%     3544.000000                 2000.000000
50%     7106.000000                 2000.000000
75%    10650.000000                 2000.000000
max    14222.000000                 2000.000000

In [18]:
df_vagas[:5]

,id,informacoes_basicas_data_requicisao,informacoes_basicas_limite_esperado_para_contratacao,informacoes_basicas_titulo_vaga,informacoes_basicas_vaga_sap,informacoes_basicas_cliente,informacoes_basicas_solicitante_cliente,informacoes_basicas_empresa_divisao,informacoes_basicas_requisitante,informacoes_basicas_analista_responsavel,...,perfil_vaga_demais_observacoes,perfil_vaga_viagens_requeridas,perfil_vaga_equipamentos_necessarios,beneficios_valor_venda,beneficios_valor_compra_1,beneficios_valor_compra_2,informacoes_basicas_data_inicial,informacoes_basicas_data_final,perfil_vaga_habilidades_comportamentais_necessarias,informacoes_basicas_nome_substituto
0,5185,04-05-2021,00-00-0000,Operation Lead -,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,...,100% Remoto Período – entre 5 – 6 meses,NaN,Nenhum -,-,R$,NaN,NaN,NaN,NaN,NaN
1,5184,04-05-2021,00-00-0000,Consultor PP/QM Sênior,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Yasmin da Rosa,...,• Início: Imediato • Fim: Jan/22,NaN,Nenhum -,-,R$,NaN,NaN,NaN,NaN,NaN
2,5183,04-05-2021,00-00-0000,ANALISTA PL/JR C/ SQL,Não,"Morris, Moran and Dodson",Dra. Catarina Marques,Decision São Paulo,Maria Laura Nogueira,Ana Albuquerque,...,Localização: Remoto Perfil: Analista Pleno ou ...,NaN,Nenhum -,-,R$,NaN,NaN,NaN,NaN,NaN
3,5182,04-05-2021,18-05-2021,Technical Architect - 11894809,Não,Nelson-Page,Dr. Raul Monteiro,Decision São Paulo,Cecília Freitas,Clara Rios,...,Budgeted Rate - indicate currency and type (ho...,Não,Notebook padrão -,- p/ mês (168h),fechado,NaN,18-05-2021,17-01-2022,NaN,NaN
4,5181,04-05-2021,00-00-0000,Consultor SAP AUTHORIZATION (BCA) -Pleno / Sênior,Não,Mann and Sons,Cauê Fogaça,Decision São Paulo,Maria Laura Nogueira,Srta. Bella Ferreira,...,contratação CLT full pela Decision locação rem...,Sim,Nenhum -,-,R$,NaN,NaN,NaN,NaN,NaN

## Prospects Data

In [12]:
df_prospects = pd.read_csv("./data/prospects.csv")

In [13]:
df_prospects.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14222 entries, 0 to 14221
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          14222 non-null  int64
 1   titulo      11279 non-null  object
 2   modalidade  737 non-null    object
 3   prospects   14222 non-null  object
dtypes: int64(1), object(3)
memory usage: 444.6+ KB

In [14]:
df_prospects.describe()

                 id
count  14222.000000
mean    7111.429686
std     4105.795333
min        0.000000
25%     3556.250000
50%     7111.500000
75%    10666.750000
max    14222.000000

In [22]:
df_prospects[:5]

,id,titulo,modalidade,prospects
0,4530,CONSULTOR CONTROL M,NaN,"[{'nome': 'José Vieira', 'codigo': '25632', 's..."
1,4531,2021-2607395-PeopleSoft Application Engine-Dom...,NaN,"[{'nome': 'Sra. Yasmin Fernandes', 'codigo': '..."
2,4532,NaN,NaN,[]
3,4533,2021-2605708-Microfocus Application Life Cycle...,NaN,"[{'nome': 'Arthur Almeida', 'codigo': '26338',..."
4,4534,2021-2605711-Microfocus QTP - UFT Automation T...,NaN,"[{'nome': 'Ana Luiza Vieira', 'codigo': '26361..."

In [23]:
df_prospects.iloc[4530]

id                                                          888
titulo                 Analista de Desenvolvimento Back-End Pl.
modalidade                                                  NaN
prospects     [{'nome': 'Dra. Bella da Rosa', 'codigo': '159...
Name: 4530, dtype: object

In [27]:
dict = df_prospects.iloc[4530]['prospects']
dict

"[{'nome': 'Dra. Bella da Rosa', 'codigo': '15993', 'situacao_candidado': 'Não Aprovado pelo Cliente', 'data_candidatura': '19-06-2019', 'ultima_atualizacao': '25-06-2019', 'comentario': 'Foi entrevistado por Danilo Marques Ribeiro=O candidato não tem interesse em vagas técnicas, esta procurando por novos desafios como líder/gestor.', 'recrutador': 'Liz Freitas'}, {'nome': 'Dra. Amanda da Paz', 'codigo': '15952', 'situacao_candidado': 'Inscrito', 'data_candidatura': '15-06-2019', 'ultima_atualizacao': '', 'comentario': '', 'recrutador': 'Caroline Machado'}]"