In [4]:
import pandas as pd

# Read CSV Files

## Applicants Data

In [5]:
#df_applicants = pd.read_csv("./data/applicants.csv")
import json

with open('./data/applicants.json', encoding='utf-8') as f:
    applicants = json.load(f)

df_applicants = pd.DataFrame.from_dict(applicants, orient='index')

In [7]:
df_applicants[:5]

,infos_basicas,informacoes_pessoais,informacoes_profissionais,formacao_e_idiomas,cargo_atual,cv_pt,cv_en
31000,"{'telefone_recado': '', 'telefone': '(11) 9704...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': '', 'area_atuacao': ''...","{'nivel_academico': '', 'nivel_ingles': '', 'n...",{},assistente administrativo\n\n\nsantosbatista\n...,
31001,"{'telefone_recado': '', 'telefone': '(11) 9372...",{'data_aceite': 'Cadastro anterior ao registro...,{'titulo_profissional': 'Analista Administrati...,{'nivel_academico': 'Ensino Superior Incomplet...,{},formação acadêmica\nensino médio (2º grau) em ...,
31002,"{'telefone_recado': '', 'telefone': '(11) 9239...",{'data_aceite': 'Cadastro anterior ao registro...,{'titulo_profissional': 'Administrativo | Fina...,{'nivel_academico': 'Ensino Superior Completo'...,{},objetivo: área administrativa | financeira\n\n...,
31003,"{'telefone_recado': '', 'telefone': '(11) 9810...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': 'Área administrativa',...",{'nivel_academico': 'Ensino Superior Incomplet...,{},formação\nensino médio completo\ninformática i...,
31004,"{'telefone_recado': '', 'telefone': '(11) 9251...",{'data_aceite': 'Cadastro anterior ao registro...,"{'titulo_profissional': '', 'area_atuacao': ''...","{'nivel_academico': '', 'nivel_ingles': '', 'n...",{},última atualização em 09/11/2021\n­ sp\n\nensi...,

In [6]:
df_applicants.info()

<class 'pandas.core.frame.DataFrame'>
Index: 42482 entries, 31000 to 5999
Data columns (total 7 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   infos_basicas              42482 non-null  object
 1   informacoes_pessoais       42482 non-null  object
 2   informacoes_profissionais  42482 non-null  object
 3   formacao_e_idiomas         42482 non-null  object
 4   cargo_atual                42482 non-null  object
 5   cv_pt                      42482 non-null  object
 6   cv_en                      42482 non-null  object
dtypes: object(7)
memory usage: 2.6+ MB

## Vagas Data

In [7]:
#df_vagas = pd.read_csv("./data/vagas.csv")
with open('./data/vagas.json', encoding='utf-8') as f:
    jobs = json.load(f)

df_vagas = pd.DataFrame.from_dict(jobs, orient='index')

In [8]:
df_vagas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14081 entries, 5185 to 12364
Data columns (total 3 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   informacoes_basicas  14081 non-null  object
 1   perfil_vaga          14081 non-null  object
 2   beneficios           14081 non-null  object
dtypes: object(3)
memory usage: 440.0+ KB

In [10]:
df_vagas.describe()

,informacoes_basicas,perfil_vaga,beneficios
count,14081,14081,14081
unique,13884,13258,1951
top,"{'data_requicisao': '27-11-2019', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
freq,27,12,1710

In [11]:
df_vagas[:5]

,informacoes_basicas,perfil_vaga,beneficios
5185,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5184,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5183,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."
5182,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '- p/ mês (168h)', 'valor_comp..."
5181,"{'data_requicisao': '04-05-2021', 'limite_espe...","{'pais': 'Brasil', 'estado': 'São Paulo', 'cid...","{'valor_venda': '-', 'valor_compra_1': 'R$', '..."

## Prospects Data

In [12]:
#df_prospects = pd.read_csv("./data/prospects.csv")
with open('./data/prospects.json', encoding='utf-8') as f:
    prospects = json.load(f)
    
df_prospects = pd.DataFrame.from_dict(prospects, orient='index')

In [13]:
df_prospects.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14222 entries, 4530 to 14222
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   titulo      14222 non-null  object
 1   modalidade  14222 non-null  object
 2   prospects   14222 non-null  object
dtypes: object(3)
memory usage: 444.4+ KB

In [14]:
df_prospects.describe()

       titulo modalidade prospects
count   14222      14222     14222
unique   9911          6     11229
top                             []
freq     2943      13485      2943

In [15]:
df_prospects[:5]

,titulo,modalidade,prospects
4530,CONSULTOR CONTROL M,,"[{'nome': 'José Vieira', 'codigo': '25632', 's..."
4531,2021-2607395-PeopleSoft Application Engine-Dom...,,"[{'nome': 'Sra. Yasmin Fernandes', 'codigo': '..."
4532,,,[]
4533,2021-2605708-Microfocus Application Life Cycle...,,"[{'nome': 'Arthur Almeida', 'codigo': '26338',..."
4534,2021-2605711-Microfocus QTP - UFT Automation T...,,"[{'nome': 'Ana Luiza Vieira', 'codigo': '26361..."

In [16]:
df_prospects.iloc[4530]

titulo                 Analista de Desenvolvimento Back-End Pl.
modalidade
prospects     [{'nome': 'Dra. Bella da Rosa', 'codigo': '159...
Name: 888, dtype: object

In [17]:
dict = df_prospects.iloc[4530]['prospects']
dict

[{'nome': 'Dra. Bella da Rosa',
  'codigo': '15993',
  'situacao_candidado': 'Não Aprovado pelo Cliente',
  'data_candidatura': '19-06-2019',
  'ultima_atualizacao': '25-06-2019',
  'comentario': 'Foi entrevistado por Danilo Marques Ribeiro=O candidato não tem interesse em vagas técnicas, esta procurando por novos desafios como líder/gestor.',
  'recrutador': 'Liz Freitas'},
 {'nome': 'Dra. Amanda da Paz',
  'codigo': '15952',
  'situacao_candidado': 'Inscrito',
  'data_candidatura': '15-06-2019',
  'ultima_atualizacao': '',
  'comentario': '',
  'recrutador': 'Caroline Machado'}]